# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_game_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('playerNum', models.IntegerField()),
                ('isDealer', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Game')),
            ],
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
