# Generated by Django 2.0.2 on 2018-03-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20180225_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.CharField(max_length=200),
        ),
    ]
